name: Node.js CI and CD
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: userapi/package-lock.json

    - name: List files in userapi directory
      run: ls -al userapi

    - run: npm ci --prefix userapi
    - run: npm run build --if-present --prefix userapi
    - run: npm test --prefix userapi
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379 

    # Zip the artifact for deployment
    - name: Zip artifact for deployment
      run: zip -r release.zip ./*

    # Upload the artifact for the deployment job
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-devops-project'
        slot-name: 'production'
        package: .
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b98dfed4376426bbae69e4c75d8396c }}
